In [2]:
import numpy as np
import cv2

# Face detection

In [3]:
img = cv2.imread('./images/0021.jpg')
cv2.imshow('original image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### load cascade classifier - frontal face

In [4]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [5]:
# apply cascade classifier to image
face, num_detection = face_cascade.detectMultiScale2(img)

In [6]:
print(face)

[[114  40 196 196]]


In [7]:
print(num_detection)

[89]


In [8]:
pt1 = (114, 40)
pt2 = (114+196, 40+196)

# draw the rectangle

cv2.rectangle(img, pt1, pt2,(0,255,0))

cv2.imshow('Face detection', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# draw the circle
cx = 114 + 196//2
cy = 40 + 196//2
r = 196 // 2

cv2.circle(img,(cx,cy),r,(0,255,255),2)
cv2.imshow('Face detection Circle', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Multiple Face Detection

In [10]:
grp_img = cv2.imread('./images/friends.jpg')
cv2.imshow('Friend detection', grp_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')

In [16]:
# step - 1 Apply cascade calssifier to an image

faces, num_detection = face_cascade.detectMultiScale2(grp_img, minNeighbors=8)

print("Faces ", faces)
print("Number of Detection ", num_detection)

Faces  [[128 107  95  95]
 [256  90  95  95]
 [406  93  95  95]]
Number of Detection  [95 73 55]


In [17]:
# step 2 Run a loop
for x,y,w,h, in faces:
    cv2.rectangle(grp_img, (x,y),(x+w,y+h),(0,255,255),1)

cv2.imshow('Detected faces', grp_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Face and Eye Detection

In [18]:
img = cv2.imread('./images/friends.jpg')

cv2.imshow('Original Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')

In [22]:
# step 1 = Face detection

faces, num_detection = face_cascade.detectMultiScale2(img, minNeighbors=8)

In [23]:
print(faces)
print(num_detection)

[[128 107  96  96]
 [255  90  95  95]
 [407  92  95  95]]
[104  84  71]


In [25]:
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255))
    
    # step 2 = Eye Detection
    
    face_roi = img[y:y+h, x:x+h] # cropping the image
    
    # step 3 = apply cascade classifier for eye
    eyes, num_detection_eye = eye_cascade.detectMultiScale2(face_roi)
    for ex, ey, ew, eh in eyes:
        cx = x + ex + ew//2
        cy = y + ey + eh//2
        r = eh//2
        
        cv2.circle(img, (cx,cy), r, (0,255,0))
    
# step = 3 face detection

cv2.imshow('Detected Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


## Face, eye and smile detection

In [28]:
img = cv2.imread('./images/friends.jpg')

cv2.imshow('Original Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
# step 1 = face detection

face_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('./cascade_classifier/haarcascade_eye.xml')
smile_cascae = cv2.CascadeClassifier('./cascade_classifier/haarcascade_smile.xml')


faces, num_detection = face_cascade.detectMultiScale2(img, minNeighbors=8)

for x,y,w,h in faces:
    face_roi = img[y:y+h, x:x+w].copy()
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255))
    
    # step 2 = Eye Detection
    eyes, num_detection_eye = eye_cascade.detectMultiScale2(face_roi)
    
    for ex, ey, ew, eh in eyes:
        cx = x + ex + ew//2
        cy = y + ey + eh//2
        r = eh//2
        
        cv2.circle(img, (cx,cy), r, (0,255,0))
        
    # step 3 = smile detection
    
    smiles, num_detection_smile = smile_cascae.detectMultiScale2(face_roi)
    
    for sx, sy, sw, sh in smiles:
        cv2.rectangle(img, (x+sx,y+sy), (x+sx+sw,y+sy+sh), (255,0,0))

# step 4 = show the image
cv2.imshow('Detected Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()